### ISSUE TITLE
Check profit and loss sheet

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#143]
check total profit when we dont count these things below 
- capital
- the money from last year

to know profit we generate only in this year

**Comment by writerityelena** [comment]
@writerity-watanabe 
accoutabt will give us at the beginning of Jan

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay thanks
plz share it to me as PDF or sth in google drive when you take it 
*dont share it public.

**Comment by writerityelena** [comment]
@writerity-watanabe 
for this we lack some documents, if you want they can prepare profit and loss for tomorrow but approximately ...because the official one is not finished yet 
we lack:
- Receipt for 26.04.2018 = 3499 MKD 
- Receipt for 26.04.2018 = 1500 MKD  
- Receipt 28.05.2018 = 1556 MKD (Ramstore)
- Receipt 02.06.2018 = 650 MKD (Neptun)
- Invoices from Kariera from 03 to 04.2018 (they said  they sent these through post office but nothing arrived yet)
