### ISSUE TITLE
Contract for Verica

### ISSUE THREAD

**Issue by writerityelena** [timeriver/company-management#169]

**Comment by writerityelena** [comment]
@writerity-watanabe 
what will happen with this? when can i send ? 
and if Verica calls next week to ask what should i say?

**Comment by writerity-watanabe** [comment]
@writerityelena 
- current status
Architect will send me price for construction and i need to tell client after that and get approval.
then we can send but it takes more time.

if she call her
just say waiting for total price for construction from the architect so that we our client will decide to approve to make agreement with her
