### ISSUE TITLE
Check if we can use paypal to pay to some other client in different countries p:

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/company-management#535]
paypal for business 

- maybe need to send registry of company

cannot receive from different country even if its paypal account for business? plz check again

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I did a research and:
1. Countries/regions with the ability to send payments:
If you reside in one of these countries/regions, you have the ability to link a credit card to your PayPal account and send payments. You do not have the ability to receive payments.
- Macedonia
2. Our account is PayPal Premier Account (Acceptance of an unlimited number of credit card and debit card payments, Multiple logins to allow employees to have access to the PayPal Premier Account on a limited basis, Set up subscription payments for services or content, Access to the customer service call center every day of the week, Access to a PayPal debit card, 24-hour fraud surveillance)
3. We can send money to different countries as payment.
4. We can't receive nor withdraw money in MK, because that's not regulated yet.
5. I sent email to PayPal customer support and I'm waiting for a reply.

![PayPal Macedonia](https://user-images.githubusercontent.com/45934340/54824414-1fe91b80-4cab-11e9-8238-bda0883a01c6.png)

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay, thanks

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe reply from Paypal:

Hello Writerity Inc,
Thank you for contacting PayPal.  
I can understand that you would like to know if you can receive money on a Macedonia PayPal account.
I can confirm that a Macedonia PayPal account is a "Send only" country meaning that you are able to sent money using PayPal.
I'm happy that I was able to help you and I wish you a pleasant day, 
 
Yours sincerely,  
Kathleen  
PayPal
